{% set version = "1.4.1" %}

package:
  name: eralchemy2
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/e/eralchemy2/eralchemy2-{{ version }}.tar.gz
    sha256: 1c1ee49b26287a459c5c89aa3eba3d6a9d1b8e6bd245d9fbacc6b15560fc66a5
  - folder: src
    url: https://github.com/maurerle/eralchemy2/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 7acbb46efe7dda418ac81d64fc69c346905d931b5751f1384dd358c71435b219

build:
  number: 1
  noarch: python
  script:
    - cd dist 
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - eralchemy2 = eralchemy2.main:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pygraphviz >=1.9
    - python >={{ python_min }}
    - sqlalchemy >=1.4.0
  run_constrained:
    - flask-sqlalchemy >=2.5.1
    - psycopg2 >=2.9.3

test:
  source_files:
    - src/tests
    - src/pyproject.toml
  requires:
    - flask-sqlalchemy
    - mypy
    - pip
    - psycopg2
    - pytest-cov
    - python {{ python_min }}
  imports:
    - eralchemy2
  commands:
    - pip check
    - eralchemy2 --help
    - mypy -p eralchemy2 --ignore-missing-imports
    - cd src
    - coverage run --source=eralchemy2 --branch -m pytest -vv --color=yes --tb=long -m "not external_db"
    - coverage report --show-missing --skip-covered --fail-under=75

about:
  home: https://github.com/maurerle/eralchemy2
  summary: Simple entity relation (ER) diagrams generation
  license: Apache-2.0
  license_file: dist/LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
