{% set version = "1.4.0" %}

package:
  name: eralchemy2
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/e/eralchemy2/eralchemy2-{{ version }}.tar.gz
    sha256: 9e26ab0fee3de7e19e9a8190b8058960fc183d6397ad638f2522a2fa8af908d4
  - folder: src
    url: https://github.com/maurerle/eralchemy2/archive/refs/tags/v{{ version }}.tar.gz
    sha256: e5c6c78cb462a78f834df567e1b21e987de52ae9f101398abbda545db940d38c

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - eralchemy2 = eralchemy2.main:cli

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - pygraphviz >=1.9
    - python >=3.8
    - sqlalchemy >=1.4.0
  run_constrained:
    - flask-sqlalchemy >=2.5.1
    - psycopg2 >=2.9.3

test:
  source_files:
    - src/tests
  imports:
    - eralchemy2
  commands:
    - pip check
    - eralchemy2 --help
    - mypy -p eralchemy2 --ignore-missing-imports
    - cd src && pytest -vv --cov=eralchemy2 --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not (database_to_intermediary or all_to_dot or (all_to_intermediary_db and not (sqlite or markdown or base)))" --cov-fail-under=75
  requires:
    - flask-sqlalchemy
    - mypy
    - pip
    - psycopg2
    - pytest-cov

about:
  home: https://github.com/maurerle/eralchemy2
  summary: Simple entity relation (ER) diagrams generation
  license: Apache-2.0
  license_file: dist/LICENSE.md

extra:
  recipe-maintainers:
    - bollwyvl
